#
# Ingress definitions
#
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: m-auth-rules
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /auth(/|$)(me)
            pathType: Prefix
            backend:
              service: 
                name: mimicchio-auth-service
                port:
                  name: ms2-port
---
#
# Ingress Base definitions
#
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mimicchio-rules
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/auth-url: "http://$host/auth/me"
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
spec:
  rules:
    - http:
        paths:
          - path: /ms1(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: mimicchio1-service
                port:
                  name: ms1-port
          - path: /ms2(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: mimicchio2-service
                port:
                  name: ms2-port
          - path: /auth(/|$)(.*)
            pathType: Prefix
            backend:
              service: 
                name: mimicchio-auth-service
                port:
                  name: ms2-port
---
#
# Secrets definitions
#
apiVersion: v1
kind: Secret
metadata:
  name: mimicchio-jwt-token-secret
type: Opaque
data:
  password: MDlmMjZlNDAyNTg2ZTJmYWE4ZGE0Yzk4YTM1ZjFiMjBkNmIwMzNjNjA5N2JlZmE4YmUzNDg2YTgyOTU4N2ZlMmY5MGE4MzJiZDNmZjlkNDI3MTBhNGRhMDk1YTJjZTI4NWIwMDlmMGMzNzMwY2Q5YjhlMWFmM2ViODRkZjY2MTE=
#
# Deployments Definitions Mimicchio 1
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimicchio1-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimicchio1
  template:
    metadata:
      labels:
        app: mimicchio1
    spec:
      containers:
      - name: k8s-mimicchio1
        image: mts88/mimicchio-1:1.0.3
        ports:
          - name: mimicchio1-port
            containerPort: 3000
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        env:
          - name: TOKEN_SECRET
            valueFrom:
                secretKeyRef:
                  name: mimicchio-jwt-token-secret
                  key: password
---
#
# Service definition (exposing)
#
apiVersion: v1
kind: Service
metadata: 
  name: mimicchio1-service
spec:
  ports:
    - name: ms1-port
      port: 3100
      targetPort: mimicchio1-port
      protocol: TCP
  selector:
    app: mimicchio1
  type: ClusterIP
#
# Mimicchio 1 Service autoscaler
#
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: mimicchio1-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mimicchio1
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
#
# Deployments Definitions Mimicchio 2 Kotlin
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimicchio2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimicchio2
  template:
    metadata:
      labels:
        app: mimicchio2
    spec:
      containers:
      - name: k8s-mimicchio2
        image: mts88/mimicchio-2:1.0.2
        ports:
          - name: mimicchio2-port
            containerPort: 8086
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        env:
          - name: TOKEN_SECRET
            valueFrom:
                secretKeyRef:
                  name: mimicchio-jwt-token-secret
                  key: password
---
#
# Service definition (exposing)
#
apiVersion: v1
kind: Service
metadata: 
  name: mimicchio2-service
spec:
  ports:
    - name: ms2-port
      port: 3186
      targetPort: mimicchio2-port
      protocol: TCP
  selector:
    app: mimicchio2
  type: ClusterIP
#
# Mimicchio 1 Service autoscaler
#
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: mimicchio2-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mimicchio2
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
#
# Deployments Definitions Sample2
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimicchio-auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimicchio-auth
  template:
    metadata:
      labels:
        app: mimicchio-auth
    spec:
      containers:
      - name: k8s-mimicchio-auth
        image: mts88/mimicchio-auth:1.0.8
        ports:
          - name: m-auth-port
            containerPort: 3001
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        env:
          - name: TOKEN_SECRET
            valueFrom:
                secretKeyRef:
                  name: mimicchio-jwt-token-secret
                  key: password
---
#
# Service definition Sample2 (exposing)
#
apiVersion: v1
kind: Service
metadata: 
    name: mimicchio-auth-service
spec:
    ports:
        - name: ms2-port
          port: 3101
          targetPort: m-auth-port
          protocol: TCP
    selector:
        app: mimicchio-auth
    type: ClusterIP
#
# Mimicchio Auth Service autoscaler
#
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: mimicchio-auth-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mimicchio-auth
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70